# Why TOML?
# See https://ruudvanasseldonk.com/2023/01/11/the-yaml-document-from-hell

[pre-commit.commands.biome]
run = """
pnpm exec biome check \\
  --fix \\
  --no-errors-on-unmatched \\
  --reporter=summary \\
  --staged
"""
stage_fixed = true
